---
kind: pipeline
name: mockinator

platform:
  os: linux
  arch: amd64

steps:
  - name: run tests
    image: golang
    commands:
      - go test ./...
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: umbrella-token